import type { FieldDef } from '@contentrain/types'

/**
 * Which field titles an entry.
 *
 * `@contentrain/types@1.0.0` makes `title_field` a required part of a model, so
 * the answer is declared rather than guessed. Guessing is what produced an
 * integration group titled `i-lucide-bot`, an article titled by its slug, and a
 * hero slide titled `f3a81c09d24e` — the guess cannot be fixed, only made wrong
 * differently.
 *
 * The inference below is kept anyway, one step down: hand-edited models, the
 * migration window, and projects generated by an older CLI all still exist, and
 * Studio must render them rather than fail.
 *
 * Two call sites need the same answer — the entry list and a relation's label —
 * so it lives here rather than being written twice with different opinions.
 */

/**
 * Field types that can render as text. Deliberately by meaning rather than by
 * `typeof`: `icon`, `color`, `slug` and `url` all store strings, and every one
 * of them has been picked as a title by accident.
 */
export const TITLE_FIELD_TYPES: readonly string[] = [
  'string',
  'text',
  'slug',
  'email',
  'url',
  'code',
  'markdown',
  'richtext',
]

/** The reserved `title_field` for a dictionary — the entry key is the title. */
export const DICTIONARY_TITLE_FIELD = 'key'

const NAME_LIKE = ['title', 'name', 'label', 'heading']

/**
 * Types that store a string but never read as a title when merely inferred.
 * Each is a legal `title_field` when an author names it; guessed, it is the
 * failure this contract exists to prevent — a settings singleton titled by
 * its WhatsApp URL. The same three MCP's `validate --fix` refuses to infer.
 */
const NOT_A_TITLE = new Set(['icon', 'color', 'slug', 'code', 'url'])

/**
 * Preference among displayable types, short scalars first — the order MCP's
 * backfill uses, so what Studio shows for a model without `title_field` is
 * what `validate --fix` would write into it.
 */
const TYPE_PRIORITY = ['string', 'email', 'text', 'markdown', 'richtext', 'slug', 'url', 'code']

interface TitleCandidate {
  field: string
  type: string
  required: boolean
}

/** Exact name-like key first (`title` < `name` < …), then a key carrying one as a token (`post_title`). */
function nameRank(field: string): number {
  const exact = NAME_LIKE.indexOf(field)
  if (exact !== -1) return exact
  const tokens = field.split('_')
  const token = NAME_LIKE.findIndex(hint => tokens.includes(hint))
  return token === -1 ? Number.POSITIVE_INFINITY : NAME_LIKE.length + token
}

function byRequired(a: TitleCandidate, b: TitleCandidate): number {
  return Number(b.required) - Number(a.required)
}

function byTypeThenName(a: TitleCandidate, b: TitleCandidate): number {
  const byType = TYPE_PRIORITY.indexOf(a.type) - TYPE_PRIORITY.indexOf(b.type)
  return byType !== 0 ? byType : a.field.localeCompare(b.field, 'en')
}

export interface TitleFieldModel {
  kind?: string
  fields?: Record<string, unknown> | Readonly<Record<string, unknown>> | null
  title_field?: string
}

function fieldEntries(model: TitleFieldModel | null | undefined): [string, FieldDef][] {
  if (!model?.fields) return []
  return Object.entries(model.fields as Record<string, FieldDef>)
}

/** Fields a model may legally declare as its `title_field`, for the picker. */
export function titleFieldOptions(model: TitleFieldModel | null | undefined): string[] {
  if (model?.kind === 'dictionary') return [DICTIONARY_TITLE_FIELD]
  return fieldEntries(model)
    .filter(([, def]) => TITLE_FIELD_TYPES.includes(def?.type ?? ''))
    .map(([key]) => key)
}

/**
 * Resolve which field to read an entry's title from.
 *
 * 1. what the model declares — the contract
 * 2. a name-like key (`title`, `name`, `label`, `heading`, or a key carrying
 *    one as a token), required ones first — `authors` with an optional
 *    `title` (the job title) and a required `name` is titled by `name`
 * 3. a required prose field, short scalars first
 * 4. any prose field; never a slug, url or code
 * 5. the first field, so something renders
 *
 * Rungs 2–4 are the chain MCP's `validate --fix` backfills with (required as
 * the tiebreak on every rung), so the reader here and the writer there agree
 * on what a fallback title is. Rung 5 is Studio's alone: a read path has to
 * render something, where the writer can decline and ask.
 */
export function resolveTitleFieldId(model: TitleFieldModel | null | undefined): string | null {
  const declared = model?.title_field
  if (declared && (declared === DICTIONARY_TITLE_FIELD || fieldEntries(model).some(([key]) => key === declared)))
    return declared

  const entries = fieldEntries(model)
  if (entries.length === 0) return null

  const candidates: TitleCandidate[] = entries
    .filter(([, def]) => TITLE_FIELD_TYPES.includes(def?.type ?? ''))
    .map(([field, def]) => ({ field, type: def.type, required: def.required === true }))

  const named = candidates.filter(c => Number.isFinite(nameRank(c.field)))
  if (named.length > 0) {
    return named.toSorted((a, b) => byRequired(a, b) || nameRank(a.field) - nameRank(b.field) || byTypeThenName(a, b))[0]!.field
  }

  const prose = candidates.filter(c => !NOT_A_TITLE.has(c.type))
  const required = prose.filter(c => c.required)
  if (required.length > 0) return required.toSorted(byTypeThenName)[0]!.field
  if (prose.length > 0) return prose.toSorted(byTypeThenName)[0]!.field

  return entries[0]?.[0] ?? null
}

/**
 * An entry's title.
 *
 * The last-resort scan of the entry's own values stays — it is what keeps a
 * model with no usable schema from rendering a column of identical fallbacks —
 * but it is now reached only after the declared field and the inference above.
 */
export function resolveEntryTitle(
  entry: Record<string, unknown> | null | undefined,
  model: TitleFieldModel | null | undefined,
  fallback: string,
): string {
  if (!entry) return fallback

  const fieldId = resolveTitleFieldId(model)
  if (fieldId) {
    const value = entry[fieldId]
    if (typeof value === 'string' && value.length > 0) return value
  }

  for (const value of Object.values(entry)) {
    if (typeof value === 'string' && value.length > 0 && value.length < 100) return value
  }

  return fallback
}
