import type { FieldDef } from '@contentrain/types'

/**
 * Which field titles an entry.
 *
 * `@contentrain/types@1.0.0` makes `title_field` a required part of a model, so
 * the answer is declared rather than guessed. Guessing is what produced an
 * integration group titled `i-lucide-bot`, an article titled by its slug, and a
 * hero slide titled `f3a81c09d24e` — the guess cannot be fixed, only made wrong
 * differently.
 *
 * The inference below is kept anyway, one step down: hand-edited models, the
 * migration window, and projects generated by an older CLI all still exist, and
 * Studio must render them rather than fail.
 *
 * Two call sites need the same answer — the entry list and a relation's label —
 * so it lives here rather than being written twice with different opinions.
 */

/**
 * Field types that can render as text. Deliberately by meaning rather than by
 * `typeof`: `icon`, `color`, `slug` and `url` all store strings, and every one
 * of them has been picked as a title by accident.
 */
export const TITLE_FIELD_TYPES: readonly string[] = [
  'string',
  'text',
  'slug',
  'email',
  'url',
  'code',
  'markdown',
  'richtext',
]

/** The reserved `title_field` for a dictionary — the entry key is the title. */
export const DICTIONARY_TITLE_FIELD = 'key'

const NAME_LIKE = ['title', 'name', 'label', 'heading']

/** Types that store a string but never read as a title when merely inferred. */
const NOT_A_TITLE = new Set(['icon', 'color', 'slug', 'code', 'url'])

export interface TitleFieldModel {
  kind?: string
  fields?: Record<string, unknown> | Readonly<Record<string, unknown>> | null
  title_field?: string
}

function fieldEntries(model: TitleFieldModel | null | undefined): [string, FieldDef][] {
  if (!model?.fields) return []
  return Object.entries(model.fields as Record<string, FieldDef>)
}

/** Fields a model may legally declare as its `title_field`, for the picker. */
export function titleFieldOptions(model: TitleFieldModel | null | undefined): string[] {
  if (model?.kind === 'dictionary') return [DICTIONARY_TITLE_FIELD]
  return fieldEntries(model)
    .filter(([, def]) => TITLE_FIELD_TYPES.includes(def?.type ?? ''))
    .map(([key]) => key)
}

/**
 * Resolve which field to read an entry's title from.
 *
 * 1. what the model declares — the contract
 * 2. a name-like key
 * 3. a required text field
 * 4. any text field that is not one of the string-shaped non-titles
 * 5. the first field, so something renders
 */
export function resolveTitleFieldId(model: TitleFieldModel | null | undefined): string | null {
  const declared = model?.title_field
  if (declared && (declared === DICTIONARY_TITLE_FIELD || fieldEntries(model).some(([key]) => key === declared)))
    return declared

  const entries = fieldEntries(model)
  if (entries.length === 0) return null

  for (const name of NAME_LIKE) {
    const hit = entries.find(([key, def]) => key === name && TITLE_FIELD_TYPES.includes(def?.type ?? ''))
    if (hit) return hit[0]
  }

  const required = entries.find(([, def]) => def?.required && (def.type === 'string' || def.type === 'text'))
  if (required) return required[0]

  const anyText = entries.find(([, def]) => TITLE_FIELD_TYPES.includes(def?.type ?? '') && !NOT_A_TITLE.has(def?.type ?? ''))
  if (anyText) return anyText[0]

  return entries[0]?.[0] ?? null
}

/**
 * An entry's title.
 *
 * The last-resort scan of the entry's own values stays — it is what keeps a
 * model with no usable schema from rendering a column of identical fallbacks —
 * but it is now reached only after the declared field and the inference above.
 */
export function resolveEntryTitle(
  entry: Record<string, unknown> | null | undefined,
  model: TitleFieldModel | null | undefined,
  fallback: string,
): string {
  if (!entry) return fallback

  const fieldId = resolveTitleFieldId(model)
  if (fieldId) {
    const value = entry[fieldId]
    if (typeof value === 'string' && value.length > 0) return value
  }

  for (const value of Object.values(entry)) {
    if (typeof value === 'string' && value.length > 0 && value.length < 100) return value
  }

  return fallback
}
