/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface AuthMarketing {
  headline: string
  illustration?: string
  tagline?: string
}

export interface Starters {
  id: string
  description: string
  featured?: boolean
  framework: 'astro' | 'nuxt' | 'next' | 'sveltekit' | 'vitepress'
  framework_icon: string
  image?: string
  name: string
  repo: string
  slug: string
  tags?: string[]
}

export type UiStrings = Record<string, string>

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'starters'): QueryBuilder<Starters>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'auth-marketing'): SingletonAccessor<AuthMarketing>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: 'ui-strings'): DictionaryAccessor
export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'starters'): QueryBuilder<Starters>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'auth-marketing'): SingletonAccessor<AuthMarketing>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: 'ui-strings'): DictionaryAccessor
  dictionary(model: string): DictionaryAccessor
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

