import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createContentEngine } from '../../server/utils/content-engine'
import type { GitProvider } from '../../server/providers/git'
import {
  resolveConfigPath,
  resolveContentPath,
  resolveContextPath,
  resolveMetaPath,
  resolveModelPath,
  resolveModelsDir,
} from '../../server/utils/content-paths'
import { serializeCanonical } from '../../server/utils/content-serialization'

function createGitProvider(overrides: Partial<GitProvider> = {}): GitProvider {
  return {
    getTree: vi.fn(),
    readFile: vi.fn(),
    listDirectory: vi.fn(),
    fileExists: vi.fn(),
    createBranch: vi.fn(),
    listBranches: vi.fn(),
    getBranchDiff: vi.fn(),
    mergeBranch: vi.fn(),
    deleteBranch: vi.fn(),
    commitFiles: vi.fn(),
    createPR: vi.fn(),
    mergePR: vi.fn(),
    getPermissions: vi.fn(),
    getBranchProtection: vi.fn(),
    getDefaultBranch: vi.fn(),
    detectFramework: vi.fn(),
    ...overrides,
  } as unknown as GitProvider
}

describe('content engine', () => {
  beforeEach(() => {
    vi.stubGlobal('resolveModelPath', resolveModelPath)
    vi.stubGlobal('resolveContentPath', resolveContentPath)
    vi.stubGlobal('resolveMetaPath', resolveMetaPath)
    vi.stubGlobal('resolveContextPath', resolveContextPath)
    vi.stubGlobal('resolveConfigPath', resolveConfigPath)
    vi.stubGlobal('resolveModelsDir', resolveModelsDir)
    vi.stubGlobal('serializeCanonical', serializeCanonical)
  })

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('sanitizes invalid document slugs before touching git', async () => {
    const git = createGitProvider()
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.saveDocument('docs', 'en', '!!!', {}, 'body', 'user@example.com')

    expect(result.validation.valid).toBe(false)
    expect(result.validation.errors[0]?.field).toBe('slug')
    expect(git.readFile).not.toHaveBeenCalled()
    expect(git.commitFiles).not.toHaveBeenCalled()
  })

  it('deletes merged content branches after a successful two-step merge', async () => {
    const git = createGitProvider({
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      mergeBranch: vi.fn().mockResolvedValue({
        merged: true,
        sha: 'merge-sha',
        pullRequestUrl: null,
      }),
      deleteBranch: vi.fn().mockResolvedValue(undefined),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.mergeBranch('cr/content/faq/en/1234567890-abcd')

    // Step 1: feature → contentrain
    expect(git.mergeBranch).toHaveBeenCalledWith('cr/content/faq/en/1234567890-abcd', 'contentrain')
    // Feature branch deleted after step 1
    expect(git.deleteBranch).toHaveBeenCalledWith('cr/content/faq/en/1234567890-abcd')
    // Step 2: contentrain → main
    expect(git.mergeBranch).toHaveBeenCalledWith('contentrain', 'main')
    expect(result).toEqual({
      merged: true,
      sha: 'merge-sha',
      pullRequestUrl: null,
    })
  })

  it('falls back to PR creation when branch protection blocks step 2 merge', async () => {
    const git = createGitProvider({
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      mergeBranch: vi.fn()
        // Step 1 succeeds: feature → contentrain
        .mockResolvedValueOnce({ merged: true, sha: 'step1-sha', pullRequestUrl: null })
        // Step 2 fails: contentrain → main (branch protection)
        .mockRejectedValueOnce(new Error('protected branch: not allowed')),
      deleteBranch: vi.fn().mockResolvedValue(undefined),
      createPR: vi.fn().mockResolvedValue({
        id: 'pr-1',
        url: 'https://example.com/pr/1',
      }),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.mergeBranch('cr/content/faq/en/1234567890-abcd')

    // Step 1: feature → contentrain
    expect(git.mergeBranch).toHaveBeenCalledWith('cr/content/faq/en/1234567890-abcd', 'contentrain')
    // Step 2: contentrain → main (fails, fallback to PR)
    expect(git.mergeBranch).toHaveBeenCalledWith('contentrain', 'main')
    // PR created from contentrain → main
    expect(git.createPR).toHaveBeenCalledWith(
      'contentrain',
      'main',
      'contentrain: advance content to main',
      'Auto-generated by Contentrain Studio.',
    )
    expect(result).toEqual({
      merged: false,
      sha: null,
      pullRequestUrl: 'https://example.com/pr/1',
    })
  })

  it('deletes collection entries and their meta records together', async () => {
    const commitFiles = vi.fn().mockResolvedValue({
      sha: 'commit-sha',
      message: 'delete',
      author: { name: 'bot', email: 'bot@example.com' },
      timestamp: '2026-03-25T00:00:00.000Z',
    })
    const git = createGitProvider({
      readFile: vi.fn(async (path: string) => {
        if (path.endsWith('/faq.json')) {
          return JSON.stringify({
            id: 'faq',
            name: 'FAQ',
            kind: 'collection',
            domain: 'marketing',
            i18n: true,
            fields: {},
          })
        }
        if (path.endsWith('/marketing/faq/en.json')) {
          return JSON.stringify({
            keep: { title: 'Keep' },
            drop: { title: 'Drop' },
          })
        }
        if (path.endsWith('/meta/faq/en.json')) {
          return JSON.stringify({
            keep: { status: 'published' },
            drop: { status: 'draft' },
          })
        }
        if (path.endsWith('/context.json')) {
          return JSON.stringify({ stats: { entries: 2 } })
        }
        if (path.endsWith('/config.json')) {
          return JSON.stringify({ locales: { supported: ['en'], default: 'en' } })
        }
        throw new Error(`Unexpected path: ${path}`)
      }),
      listDirectory: vi.fn().mockResolvedValue(['faq.json']),
      listBranches: vi.fn().mockResolvedValue([{ name: 'contentrain', sha: 'sha-1', protected: false }]),
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      createBranch: vi.fn().mockResolvedValue(undefined),
      commitFiles,
      getBranchDiff: vi.fn().mockResolvedValue([]),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    await engine.deleteContent('faq', 'en', ['drop'], 'user@example.com')

    expect(commitFiles).toHaveBeenCalledWith(
      expect.stringMatching(/^cr\/content\/faq\/en\//),
      expect.arrayContaining([
        expect.objectContaining({
          path: '.contentrain/content/marketing/faq/en.json',
          content: '{\n  "keep": {\n    "title": "Keep"\n  }\n}\n',
        }),
        expect.objectContaining({
          path: '.contentrain/meta/faq/en.json',
          content: '{\n  "keep": {\n    "status": "published"\n  }\n}\n',
        }),
      ]),
      expect.stringContaining('contentrain: delete 1 entries from faq [en]'),
      expect.any(Object),
    )
  })

  it('updates entry status in meta without touching content files', async () => {
    const commitFiles = vi.fn().mockResolvedValue({
      sha: 'commit-sha',
      message: 'status',
      author: { name: 'bot', email: 'bot@example.com' },
      timestamp: '2026-03-25T00:00:00.000Z',
    })
    const git = createGitProvider({
      readFile: vi.fn(async (path: string) => {
        if (path.endsWith('/faq.json')) {
          return JSON.stringify({
            id: 'faq',
            name: 'FAQ',
            kind: 'collection',
            domain: 'marketing',
            i18n: true,
            fields: {},
          })
        }
        if (path.endsWith('/meta/faq/en.json')) {
          return JSON.stringify({
            keep: { status: 'draft' },
          })
        }
        throw new Error(`Unexpected path: ${path}`)
      }),
      listBranches: vi.fn().mockResolvedValue([{ name: 'contentrain', sha: 'sha-1', protected: false }]),
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      createBranch: vi.fn().mockResolvedValue(undefined),
      commitFiles,
      getBranchDiff: vi.fn().mockResolvedValue([]),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    await engine.updateEntryStatus('faq', 'en', ['keep', 'new-entry'], 'published', 'user@example.com')

    expect(commitFiles).toHaveBeenCalledWith(
      expect.stringMatching(/^cr\/content\/faq\/en\//),
      [
        {
          path: '.contentrain/meta/faq/en.json',
          content: '{\n  "keep": {\n    "status": "published",\n    "updated_by": "user@example.com"\n  },\n  "new-entry": {\n    "status": "published",\n    "updated_by": "user@example.com"\n  }\n}\n',
        },
      ],
      expect.stringContaining('contentrain: published 2 entries in faq'),
      expect.any(Object),
    )
  })

  it('rejects locale copy on models without i18n support', async () => {
    const git = createGitProvider({
      readFile: vi.fn(async () => JSON.stringify({
        id: 'settings',
        name: 'Settings',
        kind: 'singleton',
        domain: 'system',
        i18n: false,
        fields: {},
      })),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.copyLocale('settings', 'en', 'tr', 'user@example.com')

    expect(result.validation.valid).toBe(false)
    expect(result.validation.errors[0]?.message).toBe('Model does not support i18n')
  })

  it('saves model definitions and tracks new model count in context', async () => {
    const commitFiles = vi.fn().mockResolvedValue({
      sha: 'commit-sha',
      message: 'save model',
      author: { name: 'bot', email: 'bot@example.com' },
      timestamp: '2026-03-25T00:00:00.000Z',
    })
    const git = createGitProvider({
      readFile: vi.fn(async (path: string) => {
        if (path.endsWith('/context.json')) {
          return JSON.stringify({ stats: { entries: 0 } })
        }
        if (path.endsWith('/config.json')) {
          return JSON.stringify({ locales: { supported: ['en'], default: 'en' } })
        }
        throw new Error(`Missing file: ${path}`)
      }),
      listDirectory: vi.fn().mockResolvedValue(['faq.json']),
      listBranches: vi.fn().mockResolvedValue([{ name: 'contentrain', sha: 'sha-1', protected: false }]),
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      createBranch: vi.fn().mockResolvedValue(undefined),
      commitFiles,
      getBranchDiff: vi.fn().mockResolvedValue([]),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    await engine.saveModel({
      id: 'authors',
      name: 'Authors',
      kind: 'collection',
      domain: 'marketing',
      i18n: true,
      fields: {},
    } as never, 'user@example.com')

    expect(commitFiles).toHaveBeenCalledWith(
      expect.stringMatching(/^cr\/model\/authors\//),
      expect.arrayContaining([
        expect.objectContaining({ path: '.contentrain/models/authors.json' }),
        expect.objectContaining({ path: '.contentrain/context.json' }),
      ]),
      expect.stringContaining('contentrain: save model authors'),
      expect.any(Object),
    )
  })

  it('initializes a project with config, models, content, and meta files', async () => {
    const commitFiles = vi.fn().mockResolvedValue({
      sha: 'commit-sha',
      message: 'init',
      author: { name: 'bot', email: 'bot@example.com' },
      timestamp: '2026-03-25T00:00:00.000Z',
    })
    const git = createGitProvider({
      listBranches: vi.fn().mockResolvedValue([{ name: 'contentrain', sha: 'sha-1', protected: false }]),
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      createBranch: vi.fn().mockResolvedValue(undefined),
      commitFiles,
      getBranchDiff: vi.fn().mockResolvedValue([]),
    })
    const engine = createContentEngine({ git, contentRoot: 'apps/web' })

    await engine.initProject(
      'nuxt',
      ['en', 'tr'],
      ['marketing'],
      [
        {
          id: 'faq',
          name: 'FAQ',
          kind: 'collection',
          domain: 'marketing',
          i18n: true,
          fields: {},
        },
      ] as never,
      'user@example.com',
    )

    expect(commitFiles).toHaveBeenCalledWith(
      expect.stringMatching(/^cr\/new\/init\//),
      expect.arrayContaining([
        expect.objectContaining({ path: 'apps/web/.contentrain/config.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/context.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/vocabulary.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/models/faq.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/content/marketing/faq/en.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/content/marketing/faq/tr.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/meta/faq/en.json' }),
        expect.objectContaining({ path: 'apps/web/.contentrain/meta/faq/tr.json' }),
      ]),
      expect.stringContaining('contentrain: initialize project'),
      expect.any(Object),
    )
  })
})
