import { describe, expect, it, vi } from 'vitest'
import { createContentEngine } from '../../server/utils/content-engine'
import type { GitProvider } from '../../server/providers/git'

function createGitProvider(overrides: Partial<GitProvider> = {}): GitProvider {
  return {
    getTree: vi.fn(),
    readFile: vi.fn(),
    listDirectory: vi.fn(),
    fileExists: vi.fn(),
    createBranch: vi.fn(),
    listBranches: vi.fn(),
    getBranchDiff: vi.fn(),
    mergeBranch: vi.fn(),
    deleteBranch: vi.fn(),
    commitFiles: vi.fn(),
    createPR: vi.fn(),
    mergePR: vi.fn(),
    getPermissions: vi.fn(),
    getBranchProtection: vi.fn(),
    getDefaultBranch: vi.fn(),
    detectFramework: vi.fn(),
    ...overrides,
  } as unknown as GitProvider
}

describe('content engine', () => {
  it('sanitizes invalid document slugs before touching git', async () => {
    const git = createGitProvider()
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.saveDocument('docs', 'en', '!!!', {}, 'body', 'user@example.com')

    expect(result.validation.valid).toBe(false)
    expect(result.validation.errors[0]?.field).toBe('slug')
    expect(git.readFile).not.toHaveBeenCalled()
    expect(git.commitFiles).not.toHaveBeenCalled()
  })

  it('deletes merged content branches after a successful merge', async () => {
    const git = createGitProvider({
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      mergeBranch: vi.fn().mockResolvedValue({
        merged: true,
        sha: 'merge-sha',
        pullRequestUrl: null,
      }),
      deleteBranch: vi.fn().mockResolvedValue(undefined),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.mergeBranch('contentrain/save-1234')

    expect(git.mergeBranch).toHaveBeenCalledWith('contentrain/save-1234', 'main')
    expect(git.deleteBranch).toHaveBeenCalledWith('contentrain/save-1234')
    expect(result).toEqual({
      merged: true,
      sha: 'merge-sha',
      pullRequestUrl: null,
    })
  })

  it('falls back to PR creation when branch protection blocks direct merge', async () => {
    const git = createGitProvider({
      getDefaultBranch: vi.fn().mockResolvedValue('main'),
      mergeBranch: vi.fn().mockRejectedValue(new Error('protected branch: not allowed')),
      createPR: vi.fn().mockResolvedValue({
        id: 'pr-1',
        url: 'https://example.com/pr/1',
      }),
    })
    const engine = createContentEngine({ git, contentRoot: '' })

    const result = await engine.mergeBranch('contentrain/save-1234')

    expect(git.createPR).toHaveBeenCalledWith(
      'contentrain/save-1234',
      'main',
      'contentrain: save-1234',
      'Auto-generated by Contentrain Studio.',
    )
    expect(result).toEqual({
      merged: false,
      sha: null,
      pullRequestUrl: 'https://example.com/pr/1',
    })
  })
})
