import { buildContextChange } from '@contentrain/mcp/core/context'
import type { Branch, EngineInternalContext, MergeResult } from './types'
import { BOT_AUTHOR, BRANCH_PREFIX, CONTENT_BRANCH } from './types'
import { pinReaderToContentrain } from './helpers'

/**
 * Ensure the dedicated `contentrain` branch exists and is synced with main.
 *
 * Per git-architecture.md §3.1 Step 2:
 * - If contentrain doesn't exist: create from default branch
 * - If contentrain exists: merge main -> contentrain (sync, ensures fast-forward later)
 *
 * Returns a guard function that can be called repeatedly (no-op after first run).
 */
export function createBranchGuard(ctx: EngineInternalContext) {
  let ensured = false

  return async function ensureContentBranch(): Promise<void> {
    if (ensured) return

    const branches = await ctx.git.listBranches()
    const hasContentBranch = branches.some(b => b.name === CONTENT_BRANCH)

    if (!hasContentBranch) {
      const defaultBranch = await ctx.git.getDefaultBranch()
      await ctx.git.createBranch(CONTENT_BRANCH, defaultBranch)

      // Migration: merge then delete old contentrain/* branches (ref namespace collision)
      const oldBranches = branches.filter(b => b.name.startsWith('contentrain/'))
      for (const old of oldBranches) {
        try {
          await ctx.git.mergeBranch(old.name, CONTENT_BRANCH)
        }
        catch {
          // eslint-disable-next-line no-console
          console.warn(`[contentrain] Migration: could not merge old branch ${old.name} — content may be lost`)
        }
        try {
          await ctx.git.deleteBranch(old.name)
        }
        catch { /* best-effort cleanup */ }
      }

      // Advance main to include any migrated content
      if (oldBranches.length > 0) {
        try {
          await ctx.git.mergeBranch(CONTENT_BRANCH, defaultBranch)
        }
        catch { /* branch protection may block — acceptable */ }
      }
    }
    else {
      // Sync: merge main -> contentrain (spec Step 2)
      const defaultBranch = await ctx.git.getDefaultBranch()
      try {
        await ctx.git.mergeBranch(defaultBranch, CONTENT_BRANCH)
      }
      catch {
        // No-op (already in sync) or conflict (extremely rare — different directories)
      }
    }

    ensured = true
  }
}

/**
 * List contentrain/* branches (pending changes).
 */
export async function listContentBranches(ctx: EngineInternalContext): Promise<Branch[]> {
  return ctx.git.listBranches(BRANCH_PREFIX)
}

/**
 * Two-step merge per git-architecture.md §3:
 * Step 1: cr/* -> contentrain (always immediate)
 * Step 2: contentrain -> main (may fallback to PR if branch-protected)
 */
export async function mergeBranch(ctx: EngineInternalContext, branch: string): Promise<MergeResult> {
  // Step 1: merge feature branch -> contentrain
  const step1 = await ctx.git.mergeBranch(branch, CONTENT_BRANCH)
  if (!step1.merged) {
    return { merged: false, sha: null, pullRequestUrl: null }
  }

  // Clean up feature branch after successful merge to contentrain
  try {
    await ctx.git.deleteBranch(branch)
  }
  catch {
    // Branch may have been auto-deleted
  }

  // Regenerate context.json on contentrain now that the content has
  // landed — feature branches no longer carry it (MCP 1.5.0 model), so
  // it is rebuilt here from the merged tree before main is advanced.
  await regenerateContextOnContentrain(ctx, branch)

  // Step 2: advance contentrain -> main
  const defaultBranch = await ctx.git.getDefaultBranch()
  try {
    return await ctx.git.mergeBranch(CONTENT_BRANCH, defaultBranch)
  }
  catch (e: unknown) {
    // If direct merge fails (branch protection), create PR
    const msg = e instanceof Error ? e.message : ''
    if (msg.includes('protected') || msg.includes('403') || msg.includes('not allowed')) {
      const pr = await ctx.git.createPR(
        CONTENT_BRANCH,
        defaultBranch,
        `contentrain: advance content to ${defaultBranch}`,
        'Auto-generated by Contentrain Studio.',
      )
      return { merged: false, sha: null, pullRequestUrl: pr.url }
    }
    throw e
  }
}

/**
 * Reject (delete) a content branch.
 */
export async function rejectBranch(ctx: EngineInternalContext, branch: string): Promise<void> {
  await ctx.git.deleteBranch(branch)
}

/**
 * Regenerate `context.json` deterministically on the `contentrain` branch
 * after a feature branch lands (MCP 1.5.0 model).
 *
 * Feature branches no longer carry `context.json`, which removes the
 * merge-conflict surface when parallel `cr/*` saves land. Instead the file
 * is rebuilt here from the merged `contentrain` tree so its stats
 * (model / entry counts) reflect post-merge reality. The brain cache and
 * external readers only ever read `context.json` from `contentrain`, so
 * this is the single point where it needs to be accurate.
 *
 * Best-effort: a failure (transient git error, or a concurrent
 * regeneration losing the non-fast-forward ref update) is swallowed — the
 * next merge regenerates it correctly.
 */
async function regenerateContextOnContentrain(
  ctx: EngineInternalContext,
  mergedBranch: string,
): Promise<void> {
  try {
    const reader = pinReaderToContentrain(ctx.git)
    const contextChange = await buildContextChange(reader, parseMergeOperation(mergedBranch), 'mcp-studio')

    // Skip an empty commit when the merged tree already carries an
    // identical context.json.
    try {
      const current = await reader.readFile(contextChange.path)
      if (current === contextChange.content) return
    }
    catch { /* no existing context.json — fall through and write it */ }

    await ctx.git.applyPlan({
      branch: CONTENT_BRANCH,
      changes: [contextChange],
      message: 'contentrain: regenerate context.json',
      author: BOT_AUTHOR,
      base: CONTENT_BRANCH,
    })
  }
  catch {
    // Best-effort: context.json self-heals on the next merge.
  }
}

/**
 * Derive the `context.json` lastOperation from a merged `cr/*` branch name.
 * Format: `cr/{scope}/{target}[/{locale}]/{timestamp}-{suffix}`.
 */
function parseMergeOperation(branch: string): { tool: string, model: string, locale?: string } {
  const parts = branch.split('/')
  // cr / scope / target / [locale] / timestamp-suffix
  const model = parts[2] ?? ''
  const locale = parts.length >= 5 ? parts[3] : undefined
  return { tool: 'merge', model, locale }
}
