import type { Branch, EngineInternalContext, MergeResult } from './types'
import { BRANCH_PREFIX, CONTENT_BRANCH } from './types'

/**
 * Ensure the dedicated `contentrain` branch exists and is synced with main.
 *
 * Per git-architecture.md §3.1 Step 2:
 * - If contentrain doesn't exist: create from default branch
 * - If contentrain exists: merge main -> contentrain (sync, ensures fast-forward later)
 *
 * Returns a guard function that can be called repeatedly (no-op after first run).
 */
export function createBranchGuard(ctx: EngineInternalContext) {
  let ensured = false

  return async function ensureContentBranch(): Promise<void> {
    if (ensured) return

    const branches = await ctx.git.listBranches()
    const hasContentBranch = branches.some(b => b.name === CONTENT_BRANCH)

    if (!hasContentBranch) {
      const defaultBranch = await ctx.git.getDefaultBranch()
      await ctx.git.createBranch(CONTENT_BRANCH, defaultBranch)

      // Migration: merge then delete old contentrain/* branches (ref namespace collision)
      const oldBranches = branches.filter(b => b.name.startsWith('contentrain/'))
      for (const old of oldBranches) {
        try {
          await ctx.git.mergeBranch(old.name, CONTENT_BRANCH)
        }
        catch {
          // eslint-disable-next-line no-console
          console.warn(`[contentrain] Migration: could not merge old branch ${old.name} — content may be lost`)
        }
        try {
          await ctx.git.deleteBranch(old.name)
        }
        catch { /* best-effort cleanup */ }
      }

      // Advance main to include any migrated content
      if (oldBranches.length > 0) {
        try {
          await ctx.git.mergeBranch(CONTENT_BRANCH, defaultBranch)
        }
        catch { /* branch protection may block — acceptable */ }
      }
    }
    else {
      // Sync: merge main -> contentrain (spec Step 2)
      const defaultBranch = await ctx.git.getDefaultBranch()
      try {
        await ctx.git.mergeBranch(defaultBranch, CONTENT_BRANCH)
      }
      catch {
        // No-op (already in sync) or conflict (extremely rare — different directories)
      }
    }

    ensured = true
  }
}

/**
 * List contentrain/* branches (pending changes).
 */
export async function listContentBranches(ctx: EngineInternalContext): Promise<Branch[]> {
  return ctx.git.listBranches(BRANCH_PREFIX)
}

/**
 * Two-step merge per git-architecture.md §3:
 * Step 1: cr/* -> contentrain (always immediate)
 * Step 2: contentrain -> main (may fallback to PR if branch-protected)
 */
export async function mergeBranch(ctx: EngineInternalContext, branch: string): Promise<MergeResult> {
  // Step 1: merge feature branch -> contentrain
  const step1 = await ctx.git.mergeBranch(branch, CONTENT_BRANCH)
  if (!step1.merged) {
    return { merged: false, sha: null, pullRequestUrl: null }
  }

  // Clean up feature branch after successful merge to contentrain
  try {
    await ctx.git.deleteBranch(branch)
  }
  catch {
    // Branch may have been auto-deleted
  }

  // Step 2: advance contentrain -> main
  const defaultBranch = await ctx.git.getDefaultBranch()
  try {
    return await ctx.git.mergeBranch(CONTENT_BRANCH, defaultBranch)
  }
  catch (e: unknown) {
    // If direct merge fails (branch protection), create PR
    const msg = e instanceof Error ? e.message : ''
    if (msg.includes('protected') || msg.includes('403') || msg.includes('not allowed')) {
      const pr = await ctx.git.createPR(
        CONTENT_BRANCH,
        defaultBranch,
        `contentrain: advance content to ${defaultBranch}`,
        'Auto-generated by Contentrain Studio.',
      )
      return { merged: false, sha: null, pullRequestUrl: pr.url }
    }
    throw e
  }
}

/**
 * Reject (delete) a content branch.
 */
export async function rejectBranch(ctx: EngineInternalContext, branch: string): Promise<void> {
  await ctx.git.deleteBranch(branch)
}
